{% set name = "schema-salad" %}
{% set version = "3.0.20181206233650" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aafda6ed02beac20abc3ae22f0873155acaa1a487478b2bf929d5437b837ee37

build:
  number: 1000
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - cachecontrol >=0.11.7,<0.12
    - lockfile >=0.9
    - mistune >=0.8.1
    - python
    - rdflib >=4.2.2
    - rdflib-jsonld >=0.3.0
    - requests >=1.0
    - ruamel.yaml >=0.12.4
    - setuptools
    - six >=1.8.0
    - typing >=3.6.4  # [not py37]
    - typing_extensions
    - future  # [py3k]

test:
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
